### ISSUE TITLE
GOES_DCC_Tracking_Example Notebook Issues

### ISSUE THREAD

**Issue by meteodave** [w-k-jones/tobac-flow#7]
When running the notebook, "[GOES_DCC_Tracking_Example](https://github.com/w-k-jones/tobac-flow/blob/master/examples/GOES_DCC_tracking_example.ipynb)," I have encountered the following issues:

1. `from tobac_flow.label import slice_labels`; slice_labels is not available in the current repository and this function is used later in the notebook cell 11 which starts with "`Calculate curvature filters and detect cores`."
2. In the notebook cell 11, I do not obtain the same summary values as shown in the precomputed example notebook. It is not clear why the differences exist especially for the values printed prior to the call for `slice_labels`.

Example Notebook Values:
**WVD growth above threshold: area = 21318
BT growth above threshold: area = 25179
Detected markers: area = 21228
Initial core count: 456
Core labels meeting length threshold: 96
Core labels meeting WVD growth threshold: 357**

My values:
**WVD growth above threshold: area = 9704
BT growth above threshold: area = 91754
Detected markers: area = 47073
Initial core count: 1716
Core labels meeting length threshold: 184
Core labels meeting WVD growth threshold: 344**

Note: The plots from the start of the Notebook through WVD Growth and BT Growth at cell 10 all look identical.

It may be useful to print some summary values prior to cell 11 so I can validate the tobac-flow package installation.

I am currently using Python 3.12.  

Any assistance or perspective on these issues would be appreciated.

**Comment by w-k-jones** [comment]
Hi @meteodave , thanks for reporting this. The notebook wasn't updated for the last release, which resulted in the bugs and differences that you found. I'll fix these and reupload, but when I find time in the next weeks I'll rework the examples to make them easier to maintain.

**Comment by w-k-jones** [comment]
Hi @meteodave , apologies for the delay finishing this up, but I've finished updating the GOES_DCC_Tracking_Example notebook. It should now work properly for the latest version of the code, and have better descriptions of the methods used.
